export enum TaskTypeEnum {
	CUSTOM_EMOJI = 'CUSTOM_EMOJI',
	EMOJI_NAME = 'EMOJI_NAME',
	STRING_NAME = 'STRING_NAME',
	TG_SUBSCRIPTION = 'TG_SUBSCRIPTION',
	TG_BOOST = 'TG_BOOST',
	TG_REACTION = 'TG_REACTION',
	WALLET = 'WALLET',
	REFERRAL = 'REFERRAL',
	LINK_TIME = 'LINK_TIME',
}
